db.items.find({rating:{$gt:500},price:{$lt:1000}})
db.items.find({$or:[{rating:{$gt:4}},{price:{$lt:1000}}]})
db.items.deleteOne({price:{$gt:700}})
db.items.deleteMany({name:"kamasutra 30"})
db.items.insertOne({name:"kat",sex:"high",age:40})
db.items.insertMany([{name:"urvashi",sex:"vol 420",age:32},{name:"malaika",sex:"super",age:46}])
db.anotherCollection.insertOne({a:60})
db.updateOne({name:"kat"},{sex:"watery"})
db.items.updateOne({name:"kat"},{$set:{sex:"watery"}})
db.items.updateMany({name:"urvashi"},{$set:{age:33,sex:"super high"}})